toy:
  11_250_50_1.0_1.0_TWD.csv:
    alpha: 1
    batch_size: 256
    embedding_size: 4
    h_dim: 64
    lamda: 0.7
    learning_rate: 0.001
    w_decay: 0.01
    z_dim: 32
  11_250_50_1.0_1.0_method:
    alpha: 1
    batch_size: 512
    embedding_size: 4
    h_dim: 64
    lamda: 0.5
    learning_rate: 0.001
    w_decay: 0.01
    z_dim: 32
  11_250_50_1.0_1.0_tuneTWD:
    alpha: 1
    batch_size: 4096
    embedding_size: 2
    h_dim: 64
    lamda: 0.3
    learning_rate: 0.001
    result0.3: -7.276
    w_decay: 0.01
    z_dim: 32
  11_250_50_1.0_1.0_tuneTWD.csv:
    alpha: 1
    batch_size: 256
    embedding_size: 2
    h_dim: 64
    lamda: 0.7
    learning_rate: 0.001
    w_decay: 0.01
    z_dim: 32
